import styled from 'styled-components';
import Head from 'next/head';
import {useAuthState} from 'react-firebase-hooks/auth';
import Sidebar from '../../components/Sidebar';
import ChatScreen from '../../components/ChatScreen';
import {db,auth} from '../../firebase'
import getRecipientEmail from '../../utils/getRecipientEmail';




function Chat({chat, messages}) {

    const [user] = useAuthState(auth);

    return (
        <Container>
           <Head>
        <title>WhatsApp-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp-logo.png" />
      </Head>
            <Sidebar/>
            <ChatContainer>
                <ChatScreen chat={chat} messages={messages} ></ChatScreen>
            </ChatContainer>
        </Container>
    )
}

export default Chat;

export async function getServerSideProps(context) {
    
    const ref = db.collection('chats').doc(context.query.id);

    const messagesRes= await ref.collection('messages').orderBy('timestamp', 'asc').get();

    const messages = messagesRes.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
    })).map(messages => ({
        ...messages,
        timestamp: messages.timestamp.toDate().getTime()
    }));

    
    const chatRes = await ref.get();
    const chat = {
        id: chatRes.id,
        ...chatRes.data()
    };

    
    return {
        props: {
            messages: JSON.stringify(messages),
            chat: chat,
        }
    }
}

const Container = styled.div`
display: flex;
width: 100%;

`;

const ChatContainer = styled.div`
flex: 74%;
    overflow: scroll;
    height: 91vh;

    ::-webkit-scrollbar {
        display: none;
    }
    -ms-overflow-style: none;
    scrollbar-width: none;

`;
