import Head from 'next/head'
// import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import styled from 'styled-components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp-logo.png" />
      </Head>
      <Container>
      <Sidebar></Sidebar>
      <Default>
        <WhatsappWeb>
        <img 
        src='/intro-connection-light.jpg' 
        alt=" "
        /> 
        <h1 
        style={{fontWeight: "300", fontColor: "#525252"}}
        >Keep your phone connected</h1>
        </WhatsappWeb>
        
      </Default>
      </Container>
      
      
    </div>
  )
}

const Container= styled.div`
display: flex;
position: absolute;
    width: 100%;
`;

const Default = styled.div`
position: relative; 
    display: flex;
    flex: 74%;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-color: #f8f9fa;
     /* width: 100%; */
`;

const WhatsappWeb= styled.div`
  margin-top: -46px;
  text-align: center;
`;

